# Generated by Django 5.1.4 on 2025-07-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='name',
            new_name='provider_name',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='contact_info',
            field=models.TextField(blank=True),
        ),
    ]
